### ISSUE TITLE
DSM 6.1.1-15101 broke it

### ISSUE THREAD

**Issue by KmanOz** [orobardet/dsm-reverse-proxy-websocket#1]
I can't seem to get Websockets going after the update to DSM 6.1.1-15101. Can someone come back and confirm if they have i working on DSM 6.1.1-15101.

Thanks

**Comment by orobardet** [comment]
Hi,

Most DSM upgrade reinstall the original `Portal.mustache` file. And 6.1.1-15101 is one doing it.

You just need to re-do the modification (and restart syno nginx) to enable websockets again in DSM reverse proxies.

**Comment by KmanOz** [comment]
Thanks I get that. Maybe I should have been clearer. I did modify it again but didn't seem to work in that Websockets weren't enabled. I was just trying to confirm if people do have it working with 6.1.1-15101. So you do? If so I will check again. Thank you.

**Comment by orobardet** [comment]
I upgraded to 6.1.1-15101-1 today. And I just had to change Portal.mustache to have websocket working again. I confirm it's ok on my side.

**Comment by KmanOz** [comment]
OK thank you. That's all I needed to know. I will troubleshoot my end.

**Comment by KmanOz** [comment]
OK well it seems to be my app that no longer works. Thank you
