### ISSUE TITLE
Any edit causes error

### ISSUE THREAD

**Issue by Cruv** [orobardet/dsm-reverse-proxy-websocket#13]
Here is what I get:

DSM cannot start up normally because it ran into a problem. Please contact the Synology support team for help.

I'm doing this from version DSM 6.2-23739 Update 2. I also tried just adding a .conf file to /usr/local/etc/nginx/sites-enabled and I get the same error. The only way to get things working again is to remove the file(s) and revert any changes. Could this be an apparmor issue?

**Comment by orobardet** [comment]
I applied the modification for reverse proxy websocket on my DSM 6.2-23739 Update 2, and it works.   
It seems your issue came from elsewhere. Try to locate and check the nginx log to see what's happening here.
