### ISSUE TITLE
DSM 6.2.1-23824 changed Portal.mustache

### ISSUE THREAD

**Issue by sampl3x** [orobardet/dsm-reverse-proxy-websocket#14]
It seems DSM 6.2.1-23824 changed Portal.mustache file contents :(

Can you tell me what to add now to the file so it does not show the websocket error aymore?

**Comment by orobardet** [comment]
Hi,
I can't help at the moment, this DSM version is not yet available in my region (still in 6.2.0).

**Comment by sampl3x** [comment]
You can download it from the synology site

**Comment by sampl3x** [comment]
Any updates?

**Comment by orobardet** [comment]
I just upgraded to DSM 6.2.1-23824.

I added the 3 lines in the `location` section and restarted the nginx, all as explained in the README.
No errors so far, the reverse proxy seems to work, but I can't tell if websockets works too as I do not have WS backend anymore.

You should try.

**Comment by sampl3x** [comment]
I tried it and works, i thought the structure/content isnt the same anymore as your examples and need to be re-looked at.
