### ISSUE TITLE
new DSM Version

### ISSUE THREAD

**Issue by CiquattroFPV** [orobardet/dsm-reverse-proxy-websocket#2]
Do you know if I'll upgrade to new version of DSM  6.1.1-15101-4 it not break the changes to the portal.mustache?

**Comment by orobardet** [comment]
My DSM already upgrade itself to version DSM 6.1.1-15101-4, and the Portal.mustache file has not been overwritten. But if it had been, you would have just had to re-apply the change in the file.

**Comment by CiquattroFPV** [comment]
thankss for the info..
