### ISSUE TITLE
Enable wss support

### ISSUE THREAD

**Issue by antoine-morisseau** [orobardet/dsm-reverse-proxy-websocket#3]
Hello there !

I found this repository when i googled about enabling wss support on nginx reverse proxy and i was wondering if you have any clue about that for a synology NAS ?

**Comment by orobardet** [comment]
The configuration given in this repository is supposed to works for WSS too.
I haved used it for WSS in the frontend part of the nginx rproxy (external -> nginx rproxy with WSS, nginx rproxy -> app in WS not secured).

I can't remember if I used it with a backend also in WSS.

**Comment by antoine-morisseau** [comment]
yeah my bad. i though it worked only for ws and needed another configuration to enable ssl. But after several test it work for ssl.
