### ISSUE TITLE
DSM 6.1.6-15266 Update 1

### ISSUE THREAD

**Issue by helio58** [orobardet/dsm-reverse-proxy-websocket#5]
Hi, I make the misstake to update to DSM 6.1.6-15266 Update 1
now the dsm-reverse-proxy-websocket is not working
Got the noVNC
Is possible to solve it?
Thanks

**Comment by orobardet** [comment]
Hi, 
You just need to re-apply the modification in your `/usr/syno/share/nginx/Portal.mustache` file, as the update overwrite it by a fresh one.

**Comment by helio58** [comment]
Thanks,
Have tried with your file but get the noVNC page. 
Have restart the DSM too

**Comment by helio58** [comment]
Sorry WORKING with chrome Thanks
